spring:
  application:
    name: authdb
  datasource:
    url: jdbc:postgresql://authdb:5432/authdb
    username: authUser
    password: authPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect