services:
  destination-service:
    image: "docker-spring-boot-destination-service:latest"
    build:
      context: ./destination-service
      dockerfile: Dockerfile 
    container_name: destination-service
    environment:
      - POSTGRES_USER=destinationUser
      - POSTGRES_PASSWORD=destinationPassword
    ports:
      - "8080:8080"
    depends_on:
      - destinationdb
    networks:
      - mynetwork

  destinationdb:
    image: postgres:latest
    container_name: destination-db
    environment:
      - POSTGRES_DB=destinationdb
      - POSTGRES_USER=destinationUser
      - POSTGRES_PASSWORD=destinationPassword
    ports:
      - "5432:5432"
    volumes:
      - destination-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U destinationUser -d destinationdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  customer-service:
    image: "docker-spring-boot-customer-service:latest"
    build:
      context: ./customer-service
      dockerfile: Dockerfile 
    container_name: customer-service
    environment:
      - POSTGRES_USER=customerUser
      - POSTGRES_PASSWORD=customerPassword
    ports:
      - "8081:8080"
    depends_on:
      - customerdb
    networks:
      - mynetwork

  customerdb:
    image: postgres:latest
    container_name: customer-db
    environment:
      - POSTGRES_DB=customerdb
      - POSTGRES_USER=customerUser
      - POSTGRES_PASSWORD=customerPassword
    ports:
      - "5433:5432"
    volumes:
      - customer-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U customerUser -d customerdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  destination-db-data:
  customer-db-data:

networks:
  mynetwork:
    driver: bridge