services:
  destination-service:
    build:
      context: ./destination-service
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: destination-db
    environment:
      - POSTGRES_DB=destinationdb
      - POSTGRES_USER=destinationUser
      - POSTGRES_PASSWORD=destinationPassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init_destination_db.sql:/docker-entrypoint-initdb.d/init_destination_db.sql
      - destination-db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  destination-db-data:

networks:
  mynetwork: