spring:
  application:
    name: customerdb
  datasource:
    url: jdbc:postgresql://customerdb:5432/customerdb
    username: customerUser
    password: customerPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect